---
version: '3.8'
services:
  front-react:
    build: ../task-manager
    container_name: front-react
    command: serve ./dist -l 8080
    restart: unless-stopped
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    container_name: nginx_mistrade
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
